### PR TITLE
Structures initialisation ordering fix

### PR DESCRIPTION
**Pull request by mortiy**
This PR fixes wrong initialisation order of the structures.

Particularly my issue was with `ImageAsset` which initialised before `ImageDimension`, as a result `ImageAsset.full_size` was equal no `null`, which consequently breaks `toProtoValueFormat` call.

I've fixed all other disordering as well.

UPDATE:
Updated structure-generator to use dependencies graph for correctly resolve ordering.

### CODE REVIEW

**Comment by kritzware** [comment]
Hi @mortiy, thanks for this PR!

We haven't encountered that error before, and your fix looks good. Although, I have to warn you, `struct.ts` is an autogenerated file, so at the next Google Ads API release your reordering will be reverted. 

We should look into [how the file is generated](https://github.com/Opteo/google-ads-node/blob/master/scripts/generate-structs.js), and see if we can ensure correct ordering at compile time.

**Comment by mortiy** [comment]
Oh, autogenerated...
Then be aware, that there is a recursive dependency `MatchingFunction` > `Operand` > `FunctionOperand` > `MatchingFunction` which I solved with later assignment:
https://github.com/Opteo/google-ads-node/blob/034391e659d4947f1107b9c721f2991488aee776/src/lib/struct.ts#L1634
https://github.com/Opteo/google-ads-node/blob/034391e659d4947f1107b9c721f2991488aee776/src/lib/struct.ts#L1677

**Comment by mortiy** [comment]
Hi,
I've updated generator itself.
Can someone test it and run on current Google API version?

**Comment by avermeil** [comment]
Hi @mortiy !

Thanks so much for your efforts on this. We'll take a look at it asap.

**Comment by kritzware** [comment]
Hi @mortiy, thank you very much for this PR! I've ran the tests, and the scripts on the Google Ads API v2 release locally, and it all seems to work fine.

I'm going to merge this in, recompile `struct.ts`, and publish a new version to NPM 👍

**Pull request merged**
